name: arts

on: push

jobs:
  tars:
    runs-on: ubuntu-latest
    steps:
      - name: outs
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: shas
        run: echo "SHA7=$(echo $(cd e3sm; git log --oneline  | head -n1 | cut -c1-7))" >> $GITHUB_ENV
      - name: zips
        run: |
          touch ${SHA7}-full.tar.gz
          tar --exclude=${SHA7}-full.tar.gz -zcvf ${SHA7}-full.tar.gz .
      - name: ghas
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.tar.gz
